S3/WRITEUP.md, S3/structure.md
I added another reason to the writeup about why we need to change the structure of the S3 bucket. The structure of the derived data folder was also updated with me adding the topic identification section to it.
=> added information for writeup and finished derived data structure

S3/structure.md
Realized I left the extracted data within the Raw data folder. Deleted it from the raw data folder.
=> revised structure final proposal

README.md
An S3 bucket with 3 dockets that I chose from random areas but made sure they were recent and had binary and text data.
=> added link to test s3 bucket

S3/structure.md
Added a second version of S3 bucket setup Kaleb recommended for the project.
=> Added a second version of S3 bucket setup

S3/structure.md
added a folder that separates document and comment extracted data which is what originally exist and another folder called summarized data for future versions of extracted data.
=> revised version 1 structure

static_analysis.md
I created a markdown file which instructs how to install and run flake8 locally on your computer.
=> Flake8 Documentation

S3/structure.md
Fixed formatting for Overalll Structure
=> fixed formatting md file

lambda_trigger_documentation.md
This documentation describes how to make a lambda trigger through the AWS web interface.
=> add explanation for making trigger

S3/script.py
script to turn one docket from old raw data structure to proposed new s3 bucket structure
=> rough draft of script

s3mocking.md
Check this out and make sure it is good. It documents how to use an s3 bucket locally with moto.
=> Markdown file documenting how to mock an s3 bucket locally

S3/move_test/docket_id_test.py, S3/runtime.md
Also submitted the regex pattern testing for the move script(still working on finalizing move function)
=> submitting rough draft of runtime complexities for move function 

S3/move.py, S3/move_test/list_test.py
This is a fully functional version of the script that moves everything into the Raw_data folder into the correct new structure.
=> the working version of the move.py file which incorporates where.py

dev-env/lambda_functions/orchestrator/app.py
Added the invoke call for the next function to be invoked. I am working on that invoked function now.
=> Added invoke line.

S3/where.md, S3/where_tests/where_moto_testing.py, S3/where_tests/where_test.py
Fixed minor issues in test files
=> added documentation for where.py file and the test files.

S3/move.md, S3/move.py
This write up explains the purpose of my move.py file and how to run the moto unit tests and how to do it locally to an aws s3 bucket
=> Move write

documentation/dev&prod.md
This file can be a location for inputting data about the current development and production environments for the ETL triggers.
=> create basics dev and prod file

dev-env/lambda_functions/orchestrator/app.py, dev-env/lambda_functions/orchestrator/invokedFunction.py
updated the orchestrator lambda to invoke the other lambda function and added the python file for that function.
=> updated orch and invoke

.github/workflows/aws-deploy.yml
Adds sam build to the github action, I realized that it probably will be important down the road.
=> add sam build to action

dev-env/events/s3_put_event_docket.json, dev-env/lambda_functions/sql_docket_ingest/app.py, dev-env/template.yaml
This PR makes the local trigger have a more accurate path, and should fix the S3 recursive issue that has been happening in CD.
=> Local trigger update and S3 connection fix

dev-env/template.yaml, docs/running_locally.md
I commented out the parts of the template file that were not working (these were associated with trying to set up a trigger on an existing bucket for the orchestrator) and instead the sam template now just creates its own s3 bucket in the stack. 
Additionally, I added simple docs for running the lambdas locally in a docker network.
=> update template to create s3 bucket, add local running docs

dev-env/lambda_functions/orchestrator/app.py, dev-env/lambda_functions/sql_docket_ingest/requirements.txt, docs/running_locally.md
This PR adds some important functionality to run the lambdas locally in a docker network using SAM.
=> Run Locally

dev-env/common/ETL/ingest.py, dev-env/common/ETL/lambda_function.py, dev-env/common/ETL/requirements.md, dev-env/common/ETL/utils/ingest_comment.py, dev-env/common/ETL/utils/ingest_docket.py, dev-env/common/ETL/utils/ingest_document.py, dev-env/common/ETL/utils/ingest_opensearch.py, dev-env/common/ETL/utils/opensearch.py, dev-env/common/ETL/utils/sql.py, dev-env/lambda_functions/orchestrator/app.py, dev-env/lambda_functions/sql_docket_ingest/app.py, dev-env/template.yaml
This PR added new utilities from the databases team to be able to do the ingest function. Also, it changes the s3 "object" from being a filepath to just a dictionary with the bucket and the file key, because we need those two values separated to get the file contents. It also sets up the sql_ingest function to work correctly and use the new utilities and adds the necessary permissions for the sql_ingest lambda in the template.
=> Sql ingest

dev-env/lambda_functions/orchestrator/app.py, dev-env/template.yaml
Replaced the previous static reference to the sql lambda function with one that uses the name that is created by cloud formation
=> fix reference to sql ingest function

dev-env/lambda_functions/orchestrator/app.py, dev-env/lambda_functions/sql_document_ingest/app.py, dev-env/lambda_functions/sql_document_ingest/requirements.txt, dev-env/template.yaml
Added SQL document ingest code. Will be updating it and working on more functionality for it later today.
=> adding SQL document ingest

dev-env/common_layer/python/common/ingest.py, dev-env/lambda_functions/open_search/app.py, dev-env/lambda_functions/open_search/requirements.txt, dev-env/template.yaml
Yaml may need to be fixed. Take a careful look. I believe the functionality of the app is perfect though.
=> Draft of Open Search

dev-env/common_layer/python/common/utils/opensearch.py, dev-env/lambda_functions/open_search/app.py, dev-env/lambda_functions/sql_docket_ingest/app.py, dev-env/lambda_functions/sql_document_ingest/app.py
This PR fixes the update to secrets across the opensearch and document lambdas, the document lambda is essentially identical to docket so should have no issues. Looking at the opensearch might be helpful to determine if the changes seem correct.
=> Fix Secrets

dev-env/template.yaml
This PR adds the neccesary role for the opensearch lambda function.
=> change permissions to be authorized to interact with opensearch

dev-env/events/sns_put_event_docket.json, dev-env/lambda_functions/orchestrator/app.py, dev-env/template.yaml
This PR adds some slight refactored code to allow the orchestrator to get sns requests and proccess them accordingly. Also the template file is updated to allows invocation from the mirrulations SNS service and I added a test event for testing with a docket sns invocation.
=> Sns refactor

dev-env/lambda_functions/sql_document_ingest/app.py
Added ability to add DocketID if it is missing. Let me know if anything is wrong but after checks I believe its right. I just wanna test it in prod to be sure.
=> Added ability to add docketID if needed

docs/adding_new_lambdas.md
Specify orchestrator lambda updates and template.yaml changes for a new lambda
=> Update new lambda documentation

.github/workflows/ci-tests.yml, dev-env/tests/orchestrator/test_app.py, dev-env/tests/sql_ingest/test_app.py
This PR should fix tests in sql docket ingest and the orchestrator lambda
=> Fixing tests

dev-env/lambda_functions/pdf_text_extract/app.py
lambda works but wanted to replace any \n with a space.
=> fixed the \n issue with connecting words

dev-env/template.yaml
This PR uncomments the trigger functionality and re-enables the trigger on the orchestrator. I will also be adding documentation to specify which part of the template is for the trigger and how it is used.
=> turn on trigger

dev-env/lambda_functions/orchestrator/app.py, dev-env/lambda_functions/sql_comment_ingest/app.py, dev-env/lambda_functions/sql_comment_ingest/requirements.txt, dev-env/template.yaml, dev-env/tests/orchestrator/test_app.py
Iterated off the `OpenSearchCommentFunction` to interface with the SQL database.
=> Add Lambda for SQL Comment Ingest

dev-env/lambda_functions/pdf_text_extract/app.py, dev-env/template.yaml, dev-env/tests/pdf_extract/app_test.py, dev-env/tests/pdf_extract/s3_saver_test.py
changed the role to mirrulations bucket role and added functionality for s3 bucket saver. Also added moto unit tests to ensure functionality works
=> added s3saver functionality to extracted text function

dev-env/lambda_functions/open_search/app.py, dev-env/lambda_functions/orchestrator/app.py, dev-env/lambda_functions/pdf_text_extract/app.py, dev-env/lambda_functions/sql_docket_ingest/app.py, dev-env/lambda_functions/sql_document_ingest/app.py, docs/dev&prod.md
Added in code documentation for ETL orchestrator lambda, open_search, pdf_extraction, sql_document and sql_docket lambdas
=> Added documentation for ETL Lambdas 
